default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  database: <%= ENV.fetch("DB_NAME", "assessment_task_development") %>
  <<: *default

test:
  database: <%= ENV.fetch("DB_NAME", "assessment_task_test") %>
  <<: *default

production:
  <<: *default
  database: assessment_task_production
  username: assessment_task
  password: <%= ENV['ASSESSMENT_TASK_DATABASE_PASSWORD'] %>
